@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

class Engine {
    -Sala salaCorrente
    -Mochila mochila
    -Scanner scanner
    -boolean fim
    --
    +Mochila getMochila()
    +Sala getSalaCorrente()
    +void setSalaCorrente()
    +void indicaFimDeJogo()
    +abstract void criaCenario()
    +boolean joga()
}

class Mochila {
    -String: capacidadeMaxima
    -List<Ferramenta>: ferramentas
    --
    +void adicionarFerramenta()
    +void removerFerramenta()
}

class Ferramenta {
    -String : nome
    --
    +abstract boolean usarFerramenta()
}

class FerramentaDescartavel extends Ferramenta {
    -boolean usado
    --
    +boolean usarFerramenta()
    +boolean isUsado()
}

class FerramentaEnergia extends Ferramenta {
    -double energiaAtual
    -double capacidadeMaxima
    --
    +double getEnergiaAtual()
    +double getCapacidadeMaxima()
    +boolean isSemEnergia()
    +void recarregar()
    +boolean usarFerramenta()
}

class FerramentaDescartavelOculta extends Ferramenta {
    -boolean usado
    --
    +boolean usarFerramenta()
    +boolean isUsado()
    +abstract boolean isVisivel()
}

class FerramentaOculta extends Ferramenta {
    +abstract boolean isVisivel()
}

class Objeto {
    -String nome
    -Boolean acaoOk
    -String descricaoAntesAcao
    -String descricaoDepoisAcao
    --
    +String getDescricao()
    +void setAcaoOk()
    +boolean isAcaoOk()
    +String getNome()
    +abstract boolean usarFerramenta()
}

class ObjetoDescartavel extends Objeto {
    -boolean usado
    --
    +boolean isUsado()
    +boolean usarFerramenta()
}

class ObjetoIluminavel extends Objeto {
    -boolean visivel
    --
    +void revela()
    +boolean isVisivel()
    +String getDescricao()
    +boolean usarFerramenta()
}

class ObjetoOculto extends Objeto {
    +abstract boolean isVisivel()
}

class Sala {
    -String nome
    -Map objetos
    -Map ferramentas
    -Map portas
    -Engine engine
    --
    +String getNome()
    +Map getObjetos()
    +Map getFerramentas()
    +Map getPortas()
    +Engine getEngine()
    +List objetosDisponiveis()
    +List ferramentasDisponiveis()
    +List portasDisponiveis()
    +String textoDescricao()
    +Sala vai()
    +boolean pegarFerramenta()
    +boolean usarFerramenta()
    +void usarObjeto()
}

class SalaOculta extends Sala {
    +abstract boolean isVisivel()
}


'Ferramentas
class Lanterna extends FerramentaEnergia
class Chave extends FerramentaDescartavelOculta
class Martelo extends Ferramenta
class Lapis extends FerramentaOculta
class Lupa extends Ferramenta

'Objetos
class Pote extends ObjetoDescartavel
class Espelho extends ObjetoIluminavel
class Estatua extends ObjetoIluminavel
class Pintura extends Objeto
class Estante extends ObjetoIluminavel
class Livro extends ObjetoOculto
class Cofre extends Objeto
class Pilha extends ObjetoDescartavel

'Salas
class Biblioteca extends Sala
class Porao extends SalaOculta
class SalaDeEstar extends Sala
class Jardim extends Sala
class Cozinha extends Sala
class Quarto extends Sala

Engine <|-- Jogo

@enduml
